import csv

rows = [
("What capability is an AI tool demonstrating when it turns a short product description into a complete product announcement?","single_choice","AI Foundations & Generative AI","Generative AI","easy",1,0.25,"Database indexing","Generating new content from learned patterns","Sorting existing records","Network monitoring","B","The AI is generating new text based on the instructions and patterns learned during training.","", "general","ai,generative-ai,llm"),
("A company uses one large pre-trained model as the starting point for a chatbot, document summarizer, and code assistant. What type of model is this?","single_choice","AI Foundations & Generative AI","Foundation Models","easy",1,0.25,"Rule-based model","Foundation model","Database model","Hardware model","B","A foundation model is broadly pre-trained and can be adapted to multiple downstream tasks.","","general","ai,foundation-models"),
("A team says its chatbot is powered by an LLM. What does LLM stand for?","single_choice","AI Foundations & Generative AI","LLMs","easy",1,0.25,"Large Language Model","Linear Learning Machine","Logical Language Method","Layered Learning Model","A","LLM stands for Large Language Model.","","general","ai,llm"),
("An AI assistant confidently provides a URL for a fictional Python library, but the website does not exist. What limitation does this demonstrate?","single_choice","AI Foundations & Generative AI","Hallucination","easy",1,0.25,"AI cannot process text","AI can generate plausible but incorrect information","AI cannot generate URLs","AI requires no training data","B","Generative AI can produce plausible-sounding information that is factually incorrect or fabricated.","","general","ai,hallucination"),
("A company trains a document-classification model using thousands of labeled invoices, resumes, reports, and contracts. What role do these documents play?","single_choice","AI Foundations & Generative AI","Training Data","easy",1,0.25,"Hardware configuration","Training data","Model output","User interface","B","Training data is the dataset used to teach a model patterns and relationships.","","general","ai,training-data"),
("An LLM internally breaks the sentence 'The customer placed an order yesterday' into smaller units before processing it. What are these units generally called?","single_choice","AI Foundations & Generative AI","Tokens","easy",1,0.25,"Database records","Tokens","Threads","Variables","B","Tokens are units such as words, subwords, or characters that language models process.","","general","ai,tokens"),
("A developer gives an AI assistant a very large document. After adding more text, the model can no longer consider all earlier content. What concept explains this?","single_choice","AI Foundations & Generative AI","Context Window","easy",1,0.25,"CPU cache","Context window","Database indexing","Network bandwidth","B","A context window limits how much tokenized information a model can consider at once.","","general","ai,context-window"),
("A manager says an AI that writes excellent reports must understand the world exactly like a human. Which response is most accurate?","single_choice","AI Foundations & Generative AI","AI Capabilities","medium",1,0.25,"AI understands everything exactly like humans","AI can perform many language tasks without human-like consciousness or understanding","AI is always more accurate than experts","AI cannot process natural language","B","AI systems can perform sophisticated language tasks without having human-like consciousness or understanding.","","general","ai,capabilities"),
("A company further trains a general-purpose language model on a smaller company-specific dataset so it better follows internal terminology and style. What is this process called?","single_choice","AI Foundations & Generative AI","Fine-Tuning","easy",1,0.25,"Encryption","Fine-tuning","Compilation","Indexing","B","Fine-tuning further trains a pre-trained model on task- or domain-specific data.","","general","ai,fine-tuning"),
("A developer changes a generative AI parameter and notices that low values produce consistent responses while higher values produce more varied responses. Which parameter is being changed?","single_choice","AI Foundations & Generative AI","Temperature","easy",1,0.25,"Server temperature","Generation temperature","Database temperature","Network latency","B","Temperature controls the randomness or variability of generated output.","","general","ai,temperature"),
("An HR employee gives an AI a list of points and asks it to turn them into a polished employee announcement. What capability is being used?","single_choice","AI Foundations & Generative AI","Generative AI Applications","easy",1,0.25,"Sorting employee IDs","Generating new text from instructions","Checking server status","Calculating CPU utilization","B","Generating a new announcement from input instructions is a generative AI task.","","general","ai,generative-ai"),
("A support employee uploads an error screenshot and asks an AI assistant to explain it. What capability is being demonstrated?","single_choice","AI Foundations & Generative AI","Multimodal AI","easy",1,0.25,"Text-only processing","Multimodal processing","Database normalization","File compression","B","Multimodal systems can work with multiple data types such as text and images.","","general","ai,multimodal"),
("A developer asks AI for security configuration instructions and checks official documentation before applying them. Why is verification important?","single_choice","AI Foundations & Generative AI","Output Verification","easy",1,0.25,"AI outputs are guaranteed to be incorrect","AI can produce inaccurate, outdated, or unsafe information","AI cannot generate technical information","Verification makes the model faster","B","AI output should be verified because generated information can be inaccurate, outdated, or unsafe.","","general","ai,verification"),

("A Python program stores the number of items in a shopping cart, and the value changes as items are added or removed. What should store this value?","single_choice","Programming Logic & Problem Solving","Variables","easy",1,0.25,"Constant comment","Variable","Loop","Function","B","A variable is a named storage location whose value can change during program execution.","","general","programming,variables"),
("A program needs to store the number of employees currently working in an office. Which data type is normally appropriate?","single_choice","Programming Logic & Problem Solving","Data Types","easy",1,0.25,"Integer","Class","Function","Array only","A","An integer is appropriate for storing a whole-number employee count.","","general","programming,data-types"),
("Before implementing a salary calculation system, a developer writes plain-language steps describing inputs, conditions, and outputs. What is this approach called?","single_choice","Programming Logic & Problem Solving","Pseudocode","easy",1,0.25,"Machine code","Pseudocode","SQL query","Network protocol","B","Pseudocode is an informal way of expressing algorithmic logic before implementation.","","general","programming,pseudocode"),
("A developer compares an integer 25 with the string '25' and expects them to be identical. What issue should the developer recognize?","single_choice","Programming Logic & Problem Solving","Type Mismatch","easy",1,0.25,"The values have different data types","Python deletes the string","The comparison always returns true","Python converts everything to Boolean","A","The integer and string represent different data types and should not automatically be treated as identical.","","general","programming,data-types"),
("A payroll application calculates an incorrect salary. The developer locates the faulty logic, changes it, and retests the program. What activity is this?","single_choice","Programming Logic & Problem Solving","Debugging","easy",1,0.25,"Deployment","Debugging","Database backup","Compilation only","B","Debugging involves identifying and fixing errors or unexpected behavior.","","general","programming,debugging"),
("A developer writes `for i in range(1, 5): print(i)` and wants to print values from 1 through 4. What is the output?","single_choice","Programming Logic & Problem Solving","Loops","easy",1,0.25,"1, 2, 3, 4, 5","1, 2, 3, 4","0, 1, 2, 3, 4","2, 3, 4, 5","B","Python range stops before the upper bound, so the loop prints 1 through 4.","for i in range(1, 5):\n    print(i)","python","python,loops,range"),
("A function calculates `result = a + b` but returns `None` when called. What is the most likely problem?","single_choice","Programming Logic & Problem Solving","Debugging","easy",1,0.25,"Python does not support addition","The function does not return result","The function has too many parameters","The variables are invalid","B","A Python function returns None when it reaches the end without an explicit return statement.","def add(a, b):\n    result = a + b","python","python,debugging,functions"),
("A developer wants to process exactly 10 records but accidentally processes 11. What type of problem is this?","single_choice","Programming Logic & Problem Solving","Off-by-One Errors","easy",1,0.25,"Syntax error","Off-by-one error","Compilation error","Hardware error","B","An off-by-one error occurs when an index or loop executes one time too many or too few.","","general","programming,debugging"),
("A registration form must reject an age of -5, the text 'abc', and an empty value before processing. What should the backend implement?","single_choice","Programming Logic & Problem Solving","Input Validation","easy",1,0.25,"Input validation","Automatic deletion","Randomization","Debugging only","A","Input validation checks whether incoming data meets expected format and business rules.","","general","programming,input-validation"),
("A website displays 'Adult' when age is at least 18 and 'Minor' otherwise. What programming concept is being used?","single_choice","Programming Logic & Problem Solving","Conditional Logic","easy",1,0.25,"Infinite looping","Conditional branching","Sorting","Age calculation only","B","An if/else condition selects one of two paths based on a condition.","","general","programming,conditions"),
("A developer wants execution to pause immediately before a suspicious line so variable values can be inspected. What should be used?","single_choice","Programming Logic & Problem Solving","Debugging Tools","easy",1,0.25,"Breakpoint","Compiler","Database index","API key","A","A breakpoint pauses execution at a selected line for inspection during debugging.","","general","debugging,breakpoints"),
("A developer runs `total = 0` and then adds 1, 2, and 3 to total in a loop. What is printed?","single_choice","Programming Logic & Problem Solving","Loops and Accumulators","easy",1,0.25,"3","6","123","Error","B","The accumulator becomes 0 + 1 + 2 + 3, resulting in 6.","total = 0\nfor amount in [1, 2, 3]:\n    total += amount\nprint(total)","python","python,loops,accumulator"),
("A while loop prints 1 forever because the loop variable is never changed. What is the likely cause?","single_choice","Programming Logic & Problem Solving","Infinite Loops","easy",1,0.25,"The loop condition never becomes false","Too many variables","The print function creates a loop","Python does not support while loops","A","If the loop variable is never updated, the condition can remain true indefinitely.","count = 1\nwhile count <= 5:\n    print(count)","python","python,loops,infinite-loop"),

("A developer asks an AI assistant only 'Fix my code' and receives an unhelpful answer. What should be added to the prompt?","single_choice","Prompt Engineering & AI Productivity","Prompt Quality","easy",1,0.25,"Less information","Relevant context and specific instructions","Only the word fix","A request for the AI to guess requirements","B","Clear context, requirements, expected behavior, and relevant code make prompts more useful.","","general","prompt-engineering,ai-productivity"),
("A developer wants an AI to create a FastAPI endpoint with validation and error handling. Which prompt is most useful?","single_choice","Prompt Engineering & AI Productivity","Prompt Structure","easy",1,0.25,"API","Write a Python FastAPI POST endpoint that creates a user, validates email, and returns JSON with error handling","Code something","Make backend","B","The detailed prompt provides technology, operation, requirements, and expected behavior.","","general","prompt-engineering,fastapi"),
("A developer tells AI that an application uses FastAPI, PostgreSQL, JWT authentication, and is a school management system before asking for an endpoint. Why?","single_choice","Prompt Engineering & AI Productivity","Context Setting","easy",1,0.25,"To change the AI programming language","To provide relevant background information","To increase CPU speed","To configure the database automatically","B","Context helps the model tailor its response to the actual application environment.","","general","prompt-engineering,context"),
("An IDE automatically suggests Python code while a developer types. What type of tool is being used?","single_choice","Prompt Engineering & AI Productivity","AI Coding Assistants","easy",1,0.25,"Version control","AI-powered coding assistant","Database server","Cloud storage","B","AI coding assistants provide code completions and suggestions inside development environments.","","general","ai,coding-assistant"),
("An AI coding assistant generates a discount function but fails to handle negative prices. What should the developer do?","single_choice","Prompt Engineering & AI Productivity","AI Code Review","easy",1,0.25,"Deploy immediately","Review, test, and modify the generated code","Assume the AI handled every edge case","Delete the project","B","AI-generated code should be reviewed and tested like any other code.","","general","ai,coding,testing"),
("A developer asks AI to fix an average function that crashes on an empty list and requests both the cause and corrected code. Why is this prompt effective?","single_choice","Prompt Engineering & AI Productivity","Coding Prompts","medium",1,0.25,"It contains no requirements","It specifies the bug, expected behavior, and desired explanation","It asks AI to guess","It uses only a keyword","B","A strong coding prompt describes the problem, expected behavior, and requested output.","def calculate_average(numbers):\n    return sum(numbers) / len(numbers)","python","prompt-engineering,debugging,python"),
("A classification prompt contains three examples showing exactly how customer complaints should be classified before the new complaint is provided. What technique is this?","single_choice","Prompt Engineering & AI Productivity","Few-Shot Prompting","medium",1,0.25,"Zero-shot prompting","Few-shot prompting","Random prompting","Batch compilation","B","Few-shot prompting provides a small number of examples to guide the model's expected behavior or format.","","general","prompt-engineering,few-shot"),
("An AI coding assistant generates SQL that directly inserts user input into a query, creating a possible SQL injection vulnerability. What should the developer do?","single_choice","Prompt Engineering & AI Productivity","AI-Assisted Security","medium",1,0.25,"Deploy because AI generated it","Review and correct the implementation using a secure approach","Ignore the issue","Remove all database functionality","B","AI-generated code can contain security vulnerabilities and must be reviewed before use.","","general","ai,security,sql-injection"),
("A developer receives an IndexError and gives the AI the error message, relevant code, expected result, and actual result. Why is this better than saying 'It doesn't work'?","single_choice","Prompt Engineering & AI Productivity","AI Debugging","easy",1,0.25,"It gives the AI more relevant evidence for diagnosis","It prevents AI from reading code","It makes Python faster","It guarantees the AI is correct","A","Error details and expected versus actual behavior give the AI useful context for troubleshooting.","","general","ai,debugging,prompt-engineering"),
("An AI initially generates an API without authentication. The developer asks it to keep the design but add JWT authentication. What technique is this?","single_choice","Prompt Engineering & AI Productivity","Iterative Prompting","easy",1,0.25,"Iterative prompting","Database normalization","Compilation","Hashing","A","Iterative prompting refines a result through follow-up instructions based on earlier output.","","general","prompt-engineering,iteration"),
("A developer uses AI to generate a database query, checks it against the schema, and tests it with sample data. What does this demonstrate?","single_choice","Prompt Engineering & AI Productivity","Human-AI Collaboration","easy",1,0.25,"Blind trust in AI","Human judgment combined with AI assistance","Complete automation","Avoidance of testing","B","The developer treats AI as an assistant while retaining responsibility for validation and correctness.","","general","ai,human-in-the-loop"),
("A junior developer copies AI-generated code without understanding it, and hidden bugs appear in production. What risk is demonstrated?","single_choice","Prompt Engineering & AI Productivity","AI Over-Reliance","medium",1,0.25,"AI always improves quality","Over-reliance can reduce understanding and introduce unnoticed problems","AI eliminates testing","AI code cannot contain bugs","B","Over-reliance on AI can reduce developer understanding and allow subtle defects to propagate.","","general","ai,coding,risks"),

("A browser needs to return to the most recently visited page first when the Back button is pressed. Which data structure best models this behavior?","single_choice","Data Structures & Algorithms","Stacks","easy",1,0.25,"Queue","Stack","Hash table","Graph","B","A stack follows LIFO, so the most recently added page is removed first.","","general","data-structures,stack"),
("A developer stores one million employee IDs in an array and accesses the element at index 500000. What is typical direct-index access complexity?","single_choice","Data Structures & Algorithms","Arrays","easy",1,0.25,"O(n)","O(1)","O(log n)","O(n²)","B","Array indexing provides direct access, which is typically O(1).","","general","arrays,time-complexity"),
("A company stores one million sorted customer IDs and needs to efficiently determine whether an ID exists. Which algorithm is appropriate?","single_choice","Data Structures & Algorithms","Searching","easy",1,0.25,"Linear search","Binary search","Bubble sort","Random search","B","Binary search repeatedly halves the search range and requires sorted data.","","general","searching,binary-search"),
("An application frequently needs to find a customer using a unique customer ID and wants average constant-time lookup. Which structure is appropriate?","single_choice","Data Structures & Algorithms","Hashing","easy",1,0.25,"Hash table","Stack","Queue","Linked list only","A","Hash tables provide expected O(1) lookup under typical hashing assumptions.","","general","hashing,data-structures"),
("A developer needs to sort a large collection and wants an algorithm with average O(n log n) complexity. Which option fits?","single_choice","Data Structures & Algorithms","Sorting","medium",1,0.25,"Bubble Sort","Merge Sort","Selection Sort","Linear Search","B","Merge Sort has O(n log n) time complexity in its standard implementation.","","general","sorting,merge-sort,time-complexity"),
("Algorithm A uses a few variables while Algorithm B creates an additional array proportional to input size. Which concept compares their memory requirements?","single_choice","Data Structures & Algorithms","Space Complexity","easy",1,0.25,"Time complexity","Space complexity","Syntax complexity","Network complexity","B","Space complexity describes how an algorithm's memory usage grows with input size.","","general","space-complexity,algorithms"),
("An e-commerce team divides a large system into authentication, product catalog, cart, payment, and order management. What problem-solving technique is this?","single_choice","Data Structures & Algorithms","Problem Decomposition","easy",1,0.25,"Problem decomposition","Randomization","Recursion only","Data duplication","A","Breaking a complex problem into smaller manageable components is problem decomposition.","","general","problem-solving,decomposition"),
("A developer analyzes logs and notices that errors frequently occur after a particular API request. What skill is being applied?","single_choice","Data Structures & Algorithms","Pattern Recognition","easy",1,0.25,"Pattern recognition","Data deletion","Encryption","Compilation","A","Recognizing recurring relationships in data is pattern recognition.","","general","problem-solving,patterns"),
("A developer uses Bubble Sort on a large unsorted array and sees execution time grow rapidly as the input increases. What is its typical worst-case complexity?","single_choice","Data Structures & Algorithms","Sorting","easy",1,0.25,"O(n log n)","O(n²)","O(1)","O(log n)","B","Bubble Sort has O(n²) worst-case time complexity.","","general","sorting,bubble-sort,time-complexity"),
("A hospital system serves patients in the order they arrive. Which data structure best models this requirement?","single_choice","Data Structures & Algorithms","Queues","easy",1,0.25,"Stack","Queue","Hash set","Binary tree","B","A queue follows FIFO, so the first patient to enter is served first.","","general","data-structures,queue"),
("One algorithm takes approximately n operations while another takes approximately n² as input grows. Which notation describes this growth?","single_choice","Data Structures & Algorithms","Big O","easy",1,0.25,"Big O notation","HTML notation","SQL notation","JSON notation","A","Big O describes asymptotic growth of time or space requirements.","","general","algorithms,big-o"),
("Two different customer IDs are mapped by a hash function to the same hash-table bucket. What has occurred?","single_choice","Data Structures & Algorithms","Hashing","easy",1,0.25,"Hash collision","Array overflow","Stack overflow","Database deadlock","A","A collision occurs when multiple keys map to the same hash-table location.","","general","hashing,collisions"),

("A company searches internal policy documents before asking an LLM to answer employee questions. What architecture is being used?","single_choice","Advanced AI Systems","RAG","easy",1,0.25,"Random Access Generation","Retrieval-Augmented Generation","Recursive Algorithm Generation","Rule-Assisted Graphing","B","RAG retrieves relevant external information and provides it to the generation step.","","general","ai,rag,retrieval"),
("Product documentation changes weekly, so a company updates its searchable document store rather than retraining the LLM each time. Why is RAG useful?","single_choice","Advanced AI Systems","RAG Benefits","medium",1,0.25,"It eliminates language models","It allows access to current or domain-specific information","It guarantees zero errors","It prevents all hallucinations","B","RAG can retrieve current information that may not be present in the model's original training data.","","general","ai,rag,knowledge-base"),
("A customer-support AI checks an account, searches a knowledge base, creates a ticket, and sends a response. What type of system is this?","single_choice","Advanced AI Systems","AI Agents","medium",1,0.25,"Static text generator","AI agent","Database index","Compiler","B","An AI agent can use tools and take actions to achieve a goal.","","general","ai,agents"),
("A travel assistant breaks a trip request into flight, hotel, calendar, and confirmation tasks and uses tools to execute them. What concept best describes this?","single_choice","Advanced AI Systems","Agentic AI","medium",1,0.25,"Agentic AI","Static chatbot","Spreadsheet automation only","Text classification only","A","Agentic AI systems can plan and execute multi-step tasks using tools with some autonomy.","","general","ai,agentic-ai"),
("An AI system extracts customer information, passes it to validation, and then passes validated data to a database step. What is happening?","single_choice","Advanced AI Systems","Multi-Step Workflows","easy",1,0.25,"Each step operates independently","The output of one step feeds the next step","Steps execute randomly","No data moves between steps","B","In a multi-step workflow, outputs commonly become inputs for subsequent steps.","","general","ai,workflows"),
("A company wants its AI assistant to retrieve documents based on semantic similarity instead of exact keywords. Which component can help?","single_choice","Advanced AI Systems","Vector Databases","medium",1,0.25,"Vector database or search index","Printer","Spreadsheet macro","Video editor","A","Vector databases can store embeddings and support similarity-based retrieval.","","general","ai,vector-database,embeddings"),
("An AI agent needs today's exchange rate and calls a currency API instead of relying only on its training data. Why is the tool useful?","single_choice","Advanced AI Systems","AI Tools","easy",1,0.25,"It provides external or real-time information","It prevents the AI from generating text","It intentionally slows the response","It replaces the AI model entirely","A","Tools extend an AI system's capabilities by accessing external systems or performing operations.","","general","ai,tools,agents"),
("A legal department wants an AI assistant to answer questions using the latest internal procedures. Why might RAG be preferable to relying only on model training?","single_choice","Advanced AI Systems","Domain Knowledge","medium",1,0.25,"RAG guarantees zero errors","RAG can retrieve relevant current domain-specific information","RAG removes the need for prompts","RAG eliminates external information","B","RAG allows the model to use retrieved information from a current domain-specific knowledge source.","","general","ai,rag,enterprise-ai"),
("An AI assistant receives the goal 'Prepare a weekly sales report and send it to the manager.' It first identifies data retrieval, calculation, report generation, and email steps. What concept is this?","single_choice","Advanced AI Systems","Planning","medium",1,0.25,"Planning","Random execution","Data deletion","Tokenization","A","Planning involves breaking a goal into ordered actions or sub-tasks.","","general","ai,planning,agents"),
("A company allows an AI agent to modify customer subscriptions automatically. The agent misunderstands a request and changes the wrong account. What risk is demonstrated?","single_choice","Advanced AI Systems","Agent Safety","medium",1,0.25,"Autonomous agents can take incorrect actions without safeguards","AI agents cannot take actions","AI agents are always correct","Tools eliminate all risks","A","Autonomous action can create real-world consequences if permissions and safeguards are insufficient.","","general","ai,agents,safety"),
("A basic chatbot only answers questions, while another AI can search inventory, create orders, and update customer records. What distinguishes the second system?","single_choice","Advanced AI Systems","Chatbots vs Agents","easy",1,0.25,"There is no difference","It can use tools and take actions toward goals","The basic chatbot is always more powerful","Agents cannot communicate with users","B","An agent can use tools and perform actions rather than only generating conversational responses.","","general","ai,agents,chatbots"),
("An AI answers an HR policy question using a retrieved official HR document and cites that document. What concept does this demonstrate?","single_choice","Advanced AI Systems","Grounding","easy",1,0.25,"Grounding","Random generation","Model compression","Data deletion","A","Grounding anchors generated responses to trusted or retrieved information.","","general","ai,grounding,rag"),

("A developer creates a Customer class containing customer data and methods such as update_address and place_order. What programming approach is being used?","single_choice","Software Engineering Fundamentals","OOP","easy",1,0.25,"Object-Oriented Programming","Procedural database management","Network programming only","Hardware design","A","Grouping data and behavior into classes and objects is a core idea of object-oriented programming.","","general","oop,classes"),
("A banking application prevents other parts of the program from directly changing an account balance and exposes deposit and withdraw methods instead. Which OOP principle is demonstrated?","single_choice","Software Engineering Fundamentals","Encapsulation","easy",1,0.25,"Encapsulation","Randomization","Compilation","Fragmentation","A","Encapsulation restricts direct access to internal state and exposes controlled operations.","","general","oop,encapsulation"),
("A developer defines `class Employee` and later creates `employee1 = Employee()`. What is Employee?","single_choice","Software Engineering Fundamentals","Classes and Objects","easy",1,0.25,"An instance","A class or blueprint","A database record","A loop","B","A class defines the structure and behavior from which objects can be instantiated.","class Employee:\n    pass\n\nemployee1 = Employee()","python","python,oop,classes"),
("A company uses PostgreSQL to store employee, salary, and department information. What type of software is PostgreSQL?","single_choice","Software Engineering Fundamentals","DBMS","easy",1,0.25,"Data Backup Management System","Database Management System","Digital Base Management Software","Network Firewall","B","PostgreSQL is a relational database management system.","","general","dbms,postgresql"),
("A developer needs to retrieve all active employees from a database. Which SQL operation should be used?","single_choice","Software Engineering Fundamentals","SQL SELECT","easy",1,0.25,"DELETE","SELECT","DROP","ALTER","B","SELECT retrieves data from one or more database tables.","SELECT * FROM employees WHERE active = true;","sql","sql,select,dbms"),
("A developer wants only employees whose salary is greater than 50000. Which SQL clause filters the rows?","single_choice","Software Engineering Fundamentals","SQL WHERE","easy",1,0.25,"ORDER BY","WHERE","GROUP BY","SELECT only","B","WHERE applies conditions to filter rows returned by a query.","SELECT * FROM employees WHERE salary > 50000;","sql","sql,where,dbms"),
("A frontend communicates with a backend using GET, POST, PUT, and DELETE endpoints representing resources. What style of API does this most closely represent?","single_choice","Software Engineering Fundamentals","REST APIs","easy",1,0.25,"REST API","FTP API","Compiler API","Hardware API","A","REST APIs commonly model resources and use HTTP methods such as GET, POST, PUT, and DELETE.","","general","api,rest,http"),
("A mobile application wants to retrieve a user's profile without changing it. Which HTTP method is normally appropriate?","single_choice","Software Engineering Fundamentals","HTTP Methods","easy",1,0.25,"POST","GET","DELETE","PUT","B","GET is generally used to retrieve a resource.","","general","http,get,rest"),
("A user changes existing profile information and sends the updated representation to the server. Which HTTP method is commonly used?","single_choice","Software Engineering Fundamentals","HTTP Methods","easy",1,0.25,"GET","PUT","TRACE","OPTIONS","B","PUT is commonly used to update or replace an existing resource representation.","","general","http,put,rest"),
("Three developers need to track changes, use branches, and merge code. Which tool is designed for this?","single_choice","Software Engineering Fundamentals","Git","easy",1,0.25,"Git","Docker only","SQL","DNS","A","Git is a distributed version control system designed to track changes and support collaboration.","","general","git,version-control"),
("A developer stages changes and runs `git commit -m 'Fix authentication bug'`. What does the commit represent?","single_choice","Software Engineering Fundamentals","Git Commits","easy",1,0.25,"A snapshot of staged changes in repository history","Deleting the repository","Automatic deployment","Compilation","A","A commit records a snapshot of staged changes in Git history.","git commit -m \"Fix authentication bug\"","bash","git,commit"),
("A developer joins a project and needs a local copy of the remote Git repository. Which operation should be used?","single_choice","Software Engineering Fundamentals","Git Clone","easy",1,0.25,"Deleting the remote repository","Creating a local copy of the remote repository","Encrypting the repository","Automatically merging repositories","B","git clone downloads a remote repository and creates a local working copy.","git clone <repository-url>","bash","git,clone"),
("A client sends a valid request and the server successfully processes it and returns the requested data. Which status code generally indicates success?","single_choice","Software Engineering Fundamentals","HTTP Status Codes","easy",1,0.25,"404","200","500","401","B","HTTP 200 OK generally indicates that a request was successfully processed.","","general","http,status-codes"),

("A company uses AI to generate customer responses, but employees check them for accuracy, relevance, and safety before sending. What process is being performed?","single_choice","Responsible AI & AI Evaluation","Output Validation","easy",1,0.25,"Output validation","Data deletion","Model compilation","Network routing","A","Output validation checks AI-generated results before they are used or delivered.","","general","responsible-ai,validation"),
("A hiring model trained on historically unbalanced hiring data favors the better-represented group. What is a likely contributing factor?","single_choice","Responsible AI & AI Evaluation","AI Bias","medium",1,0.25,"Biased or unrepresentative training data","Excessive computing power","Faster network speed","Strong encryption","A","Training data that is skewed or unrepresentative can cause models to reproduce or amplify bias.","","general","responsible-ai,bias"),
("After deploying an AI support system, a company regularly reviews responses for accuracy, fairness, and harmful behavior. Why is this important?","single_choice","Responsible AI & AI Evaluation","AI Monitoring","easy",1,0.25,"AI never needs monitoring","Regular evaluation can identify errors, bias, and unintended harm","Monitoring makes AI unnecessary","Monitoring guarantees perfect results","B","Ongoing monitoring helps identify problems that may emerge after deployment.","","general","responsible-ai,monitoring"),
("An AI system recommends which insurance claims need additional review, but a trained employee checks the recommendation before the final decision. Why is this useful?","single_choice","Responsible AI & AI Evaluation","Human Oversight","easy",1,0.25,"Humans are always unnecessary","Human review can catch errors, bias, or harmful recommendations","AI cannot process data","Human review guarantees no mistakes","B","Human oversight provides an opportunity to detect problems before consequential decisions are finalized.","","general","responsible-ai,human-oversight"),
("A bank wants customers and regulators to understand which factors influenced an AI loan recommendation. Which concept is relevant?","single_choice","Responsible AI & AI Evaluation","Explainability","easy",1,0.25,"Explainability","Compression","Tokenization","Containerization","A","Explainability concerns how understandable a model's decisions or outputs are to people.","","general","responsible-ai,explainability"),
("An employee uses AI to draft a public technical article, then fact-checks and edits it before publishing. Why is this responsible?","single_choice","Responsible AI & AI Evaluation","AI Content Review","easy",1,0.25,"AI content never needs review","AI-generated content should be checked before being relied upon or published","AI guarantees accuracy","Human editing makes AI unnecessary","B","AI-generated content can contain inaccuracies and should be reviewed before publication.","","general","responsible-ai,content-review"),
("An AI hiring system systematically gives lower scores to qualified applicants from a particular demographic group. What could be a consequence?","single_choice","Responsible AI & AI Evaluation","Fairness","medium",1,0.25,"Automatic improvement in fairness","Unfair discrimination in hiring decisions","No effect on hiring","Elimination of all bias","B","A biased model can contribute to unfair treatment of particular groups.","","general","responsible-ai,fairness,bias"),
("A team wants to determine whether its AI behaves differently across demographic groups. Which approach helps?","single_choice","Responsible AI & AI Evaluation","Bias Evaluation","medium",1,0.25,"Use only one demographic group","Use representative data and evaluate performance across groups","Avoid evaluation","Ignore edge cases","B","Testing across representative groups helps identify differences in model behavior and performance.","","general","responsible-ai,bias,evaluation"),
("A company wants to use customer conversations for AI improvement, but some contain names, phone numbers, and financial information. What should it consider?","single_choice","Responsible AI & AI Evaluation","Data Privacy","easy",1,0.25,"Make all information public","Secure and appropriate collection and use of personal data","Share data freely","Ignore privacy requirements","B","Personal and sensitive information should be collected, stored, and used appropriately and securely.","","general","privacy,data-protection"),
("An AI tells a customer that a refund was processed, but company records show that no refund occurred. What type of AI issue is this?","single_choice","Responsible AI & AI Evaluation","Hallucination","easy",1,0.25,"Hallucination","Encryption","Network failure","Database indexing","A","The AI generated a confident factual claim that was not supported by the actual records.","","general","ai,hallucination"),
("A company creates rules covering confidential data, verification, security, and acceptable employee use of generative AI. Why are these guidelines useful?","single_choice","Responsible AI & AI Evaluation","AI Governance","easy",1,0.25,"To prevent all AI use","To support consistent, safe, and responsible AI use","To eliminate employee responsibility","To guarantee AI never makes mistakes","B","Organizational guidelines help establish consistent and responsible AI usage practices.","","general","responsible-ai,governance"),
("A team evaluates an AI answer for relevance, factual correctness, and appropriateness. What are they evaluating?","single_choice","Responsible AI & AI Evaluation","Output Quality","easy",1,0.25,"Output quality","CPU performance","Network bandwidth","Database size","A","Relevance, factual correctness, and appropriateness are dimensions of AI output quality.","","general","ai,evaluation,quality"),

("A mobile application sends GET /api/products to a backend and receives product information. Which component is the client?","single_choice","Modern Engineering Awareness","Client-Server Architecture","easy",1,0.25,"The mobile application","The database server only","The network cable","The API response","A","The client initiates requests to the server and receives responses.","","general","client-server,architecture"),
("A startup experiences a sudden increase in users and provisions additional cloud resources instead of buying physical servers. What cloud benefit is demonstrated?","single_choice","Modern Engineering Awareness","Cloud Computing","easy",1,0.25,"On-demand scalability","Elimination of networking","Requirement for physical servers","Offline-only computing","A","Cloud platforms can provide scalable resources on demand.","","general","cloud,scalability"),
("A weather application uses an API key to identify the calling application, while an authentication system issues a token representing a user's authenticated session and permissions. What is the typical distinction?","single_choice","Modern Engineering Awareness","API Keys and Tokens","medium",1,0.25,"They are always identical","An API key often identifies an application, while a token can represent authenticated identity and permissions","API keys are always more secure","Tokens are used only for encryption","B","API keys commonly identify applications, while authentication tokens can represent identity and permissions.","","general","api,authentication,tokens"),
("A user enters a domain name in a browser and the system needs to find the corresponding IP address. Which system performs this function?","single_choice","Modern Engineering Awareness","DNS","easy",1,0.25,"DNS","HTTP","FTP","Docker","A","DNS translates domain names into IP addresses and supports other domain-related lookups.","","general","networking,dns"),
("A server should accept HTTPS traffic but block unauthorized network connections according to security rules. Which component can enforce this?","single_choice","Modern Engineering Awareness","Firewalls","easy",1,0.25,"Firewall","Compiler","Database index","Text editor","A","A firewall monitors and controls network traffic based on configured security rules.","","general","cybersecurity,firewall"),
("An employee receives an email that appears to be from IT and asks for a password through a fake login page. What type of attack is this?","single_choice","Modern Engineering Awareness","Phishing","easy",1,0.25,"Phishing","Encryption","Load balancing","Database backup","A","Phishing is a social-engineering attack designed to trick users into revealing sensitive information.","","general","cybersecurity,phishing"),
("A team develops a feature in a short cycle, demonstrates it, receives stakeholder feedback, and adapts the next cycle. Which approach is this?","single_choice","Modern Engineering Awareness","Agile","easy",1,0.25,"Agile development","One-time sequential development","Manual database administration","Hardware manufacturing","A","Agile emphasizes iterative development, feedback, and adaptability.","","general","agile,software-development"),
("A Scrum team plans authentication and profile work for a two-week development period. What is the period commonly called?","single_choice","Modern Engineering Awareness","Sprints","easy",1,0.25,"Sprint","Port","Commit","Token","A","A sprint is a fixed time period in which a Scrum team works toward a defined set of goals.","","general","agile,scrum,sprint"),
("A company automates testing, deployment, monitoring, and infrastructure while encouraging close collaboration between developers and operations. What practice is this?","single_choice","Modern Engineering Awareness","DevOps","easy",1,0.25,"DevOps","Manual-only development","Frontend development only","Database normalization","A","DevOps combines development and operations practices to improve collaboration and delivery.","","general","devops,automation"),
("An application works on one developer's computer but fails elsewhere because dependencies differ. The team packages the application with its dependencies into a container. Which technology is commonly used?","single_choice","Modern Engineering Awareness","Docker","easy",1,0.25,"Docker","DNS","Git only","SQL","A","Docker containers package applications and dependencies for more consistent environments.","","general","docker,containers"),
("A developer pushes code to Git, automated tests run, and a successful build is automatically deployed to staging. What practice is this?","single_choice","Modern Engineering Awareness","CI/CD","easy",1,0.25,"CI/CD","Manual deployment only","DNS resolution","Database normalization","A","CI/CD automates integration, testing, delivery, and/or deployment steps.","","general","devops,ci-cd,automation"),
("A FastAPI application runs at localhost:8000 while PostgreSQL uses localhost:5432. What do 8000 and 5432 represent?","single_choice","Modern Engineering Awareness","Network Ports","easy",1,0.25,"Network ports","Database columns","Programming variables","IP addresses","A","Ports are logical endpoints used to direct network traffic to services or processes.","FastAPI: localhost:8000\nPostgreSQL: localhost:5432","text","networking,ports"),
("An employee reuses the same password across email, banking, GitHub, and other services. One site suffers a credential leak. Why are unique passwords important?","single_choice","Modern Engineering Awareness","Password Security","easy",1,0.25,"They reduce the risk of compromised credentials being reused against other accounts","They guarantee accounts can never be hacked","They only slow legitimate logins","They are unnecessary for important accounts","A","Unique passwords limit the damage caused when credentials from one service are compromised.","","general","cybersecurity,passwords")
]

headers = [
    "question","question_type","topic","subtopic","difficulty","marks","negative_marks",
    "option_a","option_b","option_c","option_d","correct_answer","explanation",
    "code_snippet","language","tags"
]

path = "AI_Literacy_100_Scenario_Based_Assessment.csv"
with open(path, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
    writer.writerow(headers)
    writer.writerows(rows)

print(f"Created: {path}")
print(f"Questions: {len(rows)}")
print(f"Columns: {len(headers)}")
